name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject config
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          printf 'const API_URL  = "%s";\nconst API_KEY  = "%s";\nconst BASE_URL = "/ledger/";\n(function(){const b=document.createElement("base");b.href=BASE_URL;document.head.prepend(b);})();\n' \
            "$API_URL" "$API_KEY" > config.js

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
